/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#e7bdb1",
        "on-secondary-fixed-variant": "#5d4037",
        "inverse-on-surface": "#f2f1ed",
        "surface-container-low": "#f4f4f0",
        "on-primary": "#ffffff",
        "outline": "#6c7a71",
        "on-primary-fixed": "#002113",
        "tertiary-fixed": "#fadcd2",
        "tertiary-fixed-dim": "#ddc1b7",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#2c160e",
        "tertiary-container": "#b79d94",
        "surface-container-high": "#e9e8e4",
        "on-secondary": "#ffffff",
        "surface": "#faf9f5",
        "secondary": "#77574d",
        "on-primary-fixed-variant": "#005236",
        "primary-fixed": "#6ffbbe",
        "on-surface": "#1b1c1a",
        "surface-bright": "#faf9f5",
        "primary-fixed-dim": "#4edea3",
        "on-primary-container": "#00422b",
        "inverse-primary": "#4edea3",
        "on-error": "#ffffff",
        "surface-dim": "#dbdad6",
        "surface-variant": "#e3e2df",
        "primary": "#006c49",
        "on-tertiary-container": "#47352e",
        "outline-variant": "#bbcabf",
        "on-tertiary-fixed": "#271812",
        "primary-container": "#10b981",
        "secondary-container": "#fed3c7",
        "on-secondary-container": "#795950",
        "surface-container": "#efeeea",
        "surface-container-highest": "#e3e2df",
        "tertiary": "#6f5a52",
        "on-tertiary-fixed-variant": "#56423b",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#006c49",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "secondary-fixed": "#ffdbd0",
        "inverse-surface": "#2f312e",
        "on-surface-variant": "#3c4a42",
        "background": "#faf9f5",
        "on-background": "#1b1c1a"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "xl": "40px",
        "gutter": "16px",
        "xs": "4px",
        "sm": "12px",
        "lg": "24px",
        "md": "16px",
        "container-margin": "20px",
        "base": "8px"
      },
      "fontFamily": {
        "body-lg": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-md": ["Be Vietnam Pro"],
        "body-md": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "headline-lg": ["Be Vietnam Pro"],
        "headline-lg-mobile": ["Be Vietnam Pro"],
        "headline-xl": ["Be Vietnam Pro"]
      },
      "fontSize": {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
